Update CI.yml

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -26,23 +26,43 @@ jobs:
 
   build-and-test-docker:
     runs-on: ubuntu-latest
+    outputs:
+      build-successful: ${{ steps.build.outputs.success }}
+      test-successful: ${{ steps.tests.outputs.success }}
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
 
       - name: Build the Docker image
-        run: docker build -t app .
-        # Vérification si la construction a réussi
-        if: ${{ success() }}
+        id: build
+        run: |
+          docker build -t app .
+          echo "::set-output name=success::true"
 
       - name: Run Docker container and execute tests
+        id: tests
         run: |
           docker run -d -p 8080:8080 --name my-container app
           docker run --rm -v $(pwd):/app -w /app maven:3.8.1-openjdk-17 mvn test
           docker stop my-container
           docker rm my-container
-        # Vérification si les tests ont réussi
-        if: ${{ success() }}
+          echo "::set-output name=success::true"
 
+  check-results:
+    runs-on: ubuntu-latest
+    needs: build-and-test-docker
+    steps:
       - name: Check if build or test failed
-        run: exit 1 # Forcing job to fail if previous steps were not successful
+        run: |
+          if [ "${{ needs.build-and-test-docker.outputs.build-successful }}" != "true" ]; then
+            echo "Build failed!"
+            if [ "${{ needs.build-and-test-docker.outputs.test-successful }}" != "true" ]; then
+              echo "Tests also failed!"
+            fi
+            exit 1
+          fi
+
+          if [ "${{ needs.build-and-test-docker.outputs.test-successful }}" != "true" ]; then
+            echo "Tests failed!"
+            exit 1
+          fi
