Update Déploiement.yml

diff --git a/.github/workflows/Déploiement.yml b/.github/workflows/Déploiement.yml
--- a/.github/workflows/Déploiement.yml
+++ b/.github/workflows/Déploiement.yml
@@ -8,23 +8,63 @@ on:
   workflow_dispatch:
 
 jobs:
-  CI:
+
+  run-lint:
     runs-on: ubuntu-latest
-    
     steps:
-      - name: Récupère les fichiers
+      - name: Checkout code
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+      - name: Lint Code Base
+        uses: github/super-linter@v4
+        env:
+          VALIDATE_ALL_CODEBASE: false
+          DEFAULT_BRANCH: "main"
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+  build-and-test-docker:
+    runs-on: ubuntu-latest
+    outputs:
+      build-successful: ${{ steps.build.outputs.success }}
+      test-successful: ${{ steps.tests.outputs.success }}
+    steps:
+      - name: Checkout code
         uses: actions/checkout@v4
 
-      - name: CI
-        uses: actions/github-script@v4
-        with:
-          github-token: ${{ secrets.GITHUB_TOKEN }}
-          script: |
-            const response = await octokit.request('POST /repos/{owner}/{repo}/dispatches', {
-              owner: 'owner_name',
-              repo: 'repo_name',
-              event_type: 'trigger-ci'
-            });
+      - name: Build the Docker image
+        id: build
+        run: |
+          docker build -t app .
+          echo "::set-output name=success::true"
+
+      - name: Run Docker container and execute tests
+        id: tests
+        run: |
+          docker run -d -p 8080:8080 --name my-container app
+          docker run --rm -v $(pwd):/app -w /app maven:3.8.1-openjdk-17 mvn test
+          docker stop my-container
+          docker rm my-container
+          echo "::set-output name=success::true"
+
+  check-results:
+    runs-on: ubuntu-latest
+    needs: build-and-test-docker
+    steps:
+      - name: Check if build or test failed
+        run: |
+          if [ "${{ needs.build-and-test-docker.outputs.build-successful }}" != "true" ]; then
+            echo "Build failed!"
+            if [ "${{ needs.build-and-test-docker.outputs.test-successful }}" != "true" ]; then
+              echo "Tests also failed!"
+            fi
+            exit 1
+          fi
+
+          if [ "${{ needs.build-and-test-docker.outputs.test-successful }}" != "true" ]; then
+            echo "Tests failed!"
+            exit 1
+          fi
 
   Deploiement:
     runs-on: ubuntu-latest
